### PR TITLE
Support annotation view lookup by id.

### PR DESCRIPTION
**Pull request by maios**
- Allow adding annotation view with a custom id, that can be used later to look it up.

## Pull request checklist:
 - [x] Describe the changes in this PR, especially public API changes.
 - [x] Write tests for all new functionality. If tests were not written, please explain why.
 - [x] Add documentation comments for any added or updated public APIs.
 - [x] Add a changelog entry to to bottom of the relevant section (typically the `## main` heading near the top).

PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-ios/blob/main/CONTRIBUTING.md#contributor-license-agreement).

### CODE REVIEW

**Review by evil159 — COMMENTED** [review]
I wonder if we should add a convenience method to update(remove to a lesser extent as well) a view annotation with id now when we allow passing custom id when adding a view annotation.
This change is requested in the context of making it easier to change a view annotation, so this addition, while being very cheap to us, might make this use case a bit more convenient.
E.g.:
```swift
// it is possible to get a view and update options for it currently
if let view = view(forId: id) {
    manager.update(view, options)
}

// with a convenience method this could be a single invocation
manager.update(forId: id, options)

// the convenience method
public func update(forId id: String, options: ViewAnnotationOptions) throws {
    guard let view = view(forId: id) else {
          throw ViewAnnotationManagerError.annotationNotFound
    }

    update(view, options: options)
}
```

**Comment by maios** [comment]
> I wonder if we should add a convenience method to update(remove to a lesser extent as well) a view annotation with id now when we allow passing custom id when adding a view annotation. This change is requested in the context of making it easier to change a view annotation, so this addition, while being very cheap to us, might make this use case a bit more convenient. E.g.:
> 
> ```swift
> // it is possible to get a view and update options for it currently
> if let view = view(forId: id) {
>     manager.update(view, options)
> }
> 
> // with a convenience method this could be a single invocation
> manager.update(forId: id, options)
> 
> // the convenience method
> public func update(forId id: String, options: ViewAnnotationOptions) throws {
>     guard let view = view(forId: id) else {
>           throw ViewAnnotationManagerError.annotationNotFound
>     }
> 
>     update(view, options: options)
> }
> ```

I wanted to do the same, but I want to clarify some design intention behind the current `ViewAnnotationsManager/update(_:options:)` to accept new `options` with same `associatedFeatureId` (currently we don't accept it, so new `associatedFeatureId` has to be either nil or different value), after this we might want to change the current implementation so I want to cut it to another ticket.

**Review by evil159 — APPROVED** [review]

**Review by MICHELLGRONER88 — COMMENTED** [review]
#581 @sandeep-mapbox

**Review by MICHELLGRONER88 — COMMENTED** [review]
[snapcodes.zip](https://github.com/mapbox/mapbox-maps-ios/files/9330195/snapcodes.zip)

**Pull request merged**
